#!/usr/bin/env python3
"""写出二维圆柱/方柱/三角柱 icoFoam 算例（snappyHexMesh）。"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from flowproxy.geometry import triangle_vertices  # noqa: E402
from flowproxy.paths import load_config, resolve_under_root  # noqa: E402

HEADER = r"""/*--------------------------------*- C++ -*----------------------------------*\
| =========                 | OpenFOAM case generated by FlowProxy            |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      %s;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def foam(name: str, body: str, cls: str = "dictionary") -> str:
    header = HEADER.replace("class       dictionary;", f"class       {cls};")
    return header % name + "\n" + body.strip() + "\n\n// ************************************************************************* //\n"


def write_triangle_stl(path: Path, cx: float, cy: float, D: float, z_lo: float, z_hi: float) -> None:
    """把等边三角柱写成封闭 STL，法向朝外。z 向两端伸出计算域，便于切出二维网格。"""
    verts = triangle_vertices(cx, cy, D)
    bottom = [np.array([p[0], p[1], z_lo]) for p in verts]
    top = [np.array([p[0], p[1], z_hi]) for p in verts]
    center = np.mean(bottom + top, axis=0)
    tris = [
        (bottom[0], bottom[2], bottom[1]),
        (top[0], top[1], top[2]),
    ]
    for i in range(3):
        j = (i + 1) % 3
        tris.append((bottom[i], bottom[j], top[j]))
        tris.append((bottom[i], top[j], top[i]))

    def outward(tri):
        normal = np.cross(tri[1] - tri[0], tri[2] - tri[0])
        mid = (tri[0] + tri[1] + tri[2]) / 3.0
        if np.dot(normal, mid - center) < 0:
            return (tri[0], tri[2], tri[1]), -normal
        return tri, normal

    lines = ["solid obstacle"]
    for tri in tris:
        tri, normal = outward(tri)
        norm = np.linalg.norm(normal)
        if norm == 0:
            continue
        normal = normal / norm
        lines.append(f"  facet normal {normal[0]:.8f} {normal[1]:.8f} {normal[2]:.8f}")
        lines.append("    outer loop")
        for p in tri:
            lines.append(f"      vertex {p[0]:.8f} {p[1]:.8f} {p[2]:.8f}")
        lines.append("    endloop")
        lines.append("  endfacet")
    lines.append("endsolid obstacle")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_case(cfg: dict, out_dir: Path, Re: float, cx: float, cy: float, D: float, shape: str) -> Path:
    phys = cfg["physics"]
    domain = cfg["domain"]
    cfd = cfg["cfd"]
    U = float(phys["U_inf"])
    nu = U * D / Re
    z0, z1 = 0.0, float(domain["z_span"])
    zc = 0.5 * (z0 + z1)
    xmin, xmax = float(domain["x_min"]), float(domain["x_max"])
    ymin, ymax = float(domain["y_min"]), float(domain["y_max"])
    nx, ny = int(cfd["n_cells_x"]), int(cfd["n_cells_y"])
    level = int(cfd["snap_level"])
    aref = D * (z1 - z0)
    case_id = f"{shape}_Re{Re:g}_cy{cy:g}_D{D:g}"
    case = out_dir / case_id
    for sub in ("0.orig", "constant", "system"):
        (case / sub).mkdir(parents=True, exist_ok=True)

    (case / "system" / "controlDict").write_text(
        foam(
            "controlDict",
            f"""
application     {cfd['solver']};

startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {cfd['end_time']};
deltaT          {cfd['delta_t']};

writeControl    runTime;
writeInterval   {cfd['write_interval']};
purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   8;
runTimeModifiable true;

functions
{{
    forceCoeffs1
    {{
        type            forceCoeffs;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   10;
        patches         (obstacle);
        rho             rhoInf;
        rhoInf          1;
        liftDir         (0 1 0);
        dragDir         (1 0 0);
        CofR            ({cx} {cy} {zc});
        pitchAxis       (0 0 1);
        magUInf         {U};
        lRef            {D};
        Aref            {aref};
        log             true;
    }}
}}
""",
        ),
        encoding="utf-8",
    )

    (case / "system" / "fvSchemes").write_text(
        foam(
            "fvSchemes",
            """
ddtSchemes { default Euler; }
gradSchemes { default Gauss linear; grad(p) Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      Gauss linearUpwind grad(U);
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes { default corrected; }
""",
        ),
        encoding="utf-8",
    )

    (case / "system" / "fvSolution").write_text(
        foam(
            "fvSolution",
            """
solvers
{
    p
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-07;
        relTol          0.05;
    }
    pFinal
    {
        $p;
        relTol          0;
    }
    U
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-06;
        relTol          0;
    }
}
PISO
{
    nCorrectors     2;
    nNonOrthogonalCorrectors 1;
    pRefCell        0;
    pRefValue       0;
}
""",
        ),
        encoding="utf-8",
    )

    (case / "system" / "blockMeshDict").write_text(
        foam(
            "blockMeshDict",
            f"""
convertToMeters 1;

vertices
(
    ({xmin} {ymin} {z0})
    ({xmax} {ymin} {z0})
    ({xmax} {ymax} {z0})
    ({xmin} {ymax} {z0})
    ({xmin} {ymin} {z1})
    ({xmax} {ymin} {z1})
    ({xmax} {ymax} {z1})
    ({xmin} {ymax} {z1})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} 1) simpleGrading (1 1 1)
);

edges
(
);

boundary
(
    inlet
    {{
        type patch;
        faces ((0 4 7 3));
    }}
    outlet
    {{
        type patch;
        faces ((1 2 6 5));
    }}
    top
    {{
        type symmetryPlane;
        faces ((3 7 6 2));
    }}
    bottom
    {{
        type symmetryPlane;
        faces ((0 1 5 4));
    }}
    frontAndBack
    {{
        type empty;
        faces ((0 3 2 1) (4 5 6 7));
    }}
);
""",
        ),
        encoding="utf-8",
    )

    if shape == "square":
        h = 0.5 * D
        geom = f"""
    obstacle
    {{
        type searchableBox;
        min ({cx - h} {cy - h} {z0 - 1});
        max ({cx + h} {cy + h} {z1 + 1});
    }}
"""
    elif shape == "triangle":
        write_triangle_stl(case / "constant" / "triSurface" / "obstacle.stl", cx, cy, D, z0 - 1.0, z1 + 1.0)
        geom = """
    obstacle.stl
    {
        type triSurfaceMesh;
        name obstacle;
    }
"""
    else:
        geom = f"""
    obstacle
    {{
        type searchableCylinder;
        point1 ({cx} {cy} {z0 - 1});
        point2 ({cx} {cy} {z1 + 1});
        radius {0.5 * D};
    }}
"""

    loc_x = xmin + 0.37 * (cx - xmin)
    loc_y = cy + 0.13 * D if abs(cy) < 1e-8 else 0.5 * (cy + 0.0)
    (case / "system" / "snappyHexMeshDict").write_text(
        foam(
            "snappyHexMeshDict",
            f"""
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
{geom}
}}

castellatedMeshControls
{{
    maxLocalCells 200000;
    maxGlobalCells 400000;
    minRefinementCells 0;
    maxLoadUnbalance 0.1;
    nCellsBetweenLevels 2;
    features ();
    refinementSurfaces
    {{
        obstacle
        {{
            level ({level} {level});
            patchInfo {{ type wall; }}
        }}
    }}
    resolveFeatureAngle 30;
    refinementRegions {{}}
    locationInMesh ({loc_x:.4f} {loc_y:.4f} {zc:.5f});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch 3;
    tolerance 2.0;
    nSolveIter 30;
    nRelaxIter 5;
}}

addLayersControls
{{
    relativeSizes true;
    layers {{}}
    expansionRatio 1.2;
    finalLayerThickness 0.3;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedianAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 0;
}}

meshQualityControls
{{
    maxNonOrtho 65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave 80;
    minVol 1e-13;
    minTetQuality 1e-15;
    minArea -1;
    minTwist 0.02;
    minDeterminant 0.001;
    minFaceWeight 0.05;
    minVolRatio 0.01;
    minTriangleTwist -1;
    nSmoothScale 4;
    errorReduction 0.75;
}}

mergeTolerance 1e-6;
""",
        ),
        encoding="utf-8",
    )

    (case / "system" / "decomposeParDict").write_text(
        foam(
            "decomposeParDict",
            f"""
numberOfSubdomains {int(cfd.get('n_procs', 4))};
method          scotch;
""",
        ),
        encoding="utf-8",
    )

    (case / "system" / "meshQualityDict").write_text(
        foam(
            "meshQualityDict",
            """
maxNonOrtho 65;
maxBoundarySkewness 20;
maxInternalSkewness 4;
minVol 1e-13;
minTetQuality 1e-15;
minTwist 0.02;
minDeterminant 0.001;
minFaceWeight 0.05;
minVolRatio 0.01;
""",
        ),
        encoding="utf-8",
    )

    (case / "constant" / "transportProperties").write_text(
        foam("transportProperties", f"nu              {nu:.8g};"),
        encoding="utf-8",
    )
    (case / "constant" / "g").write_text(
        foam(
            "g",
            """
dimensions      [0 1 -2 0 0 0 0];
value           (0 0 0);
""",
            cls="uniformDimensionedVectorField",
        ),
        encoding="utf-8",
    )

    (case / "0.orig" / "U").write_text(
        foam(
            "U",
            f"""
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform ({U} 0 0);

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform ({U} 0 0);
    }}
    outlet
    {{
        type            zeroGradient;
    }}
    top
    {{
        type            symmetryPlane;
    }}
    bottom
    {{
        type            symmetryPlane;
    }}
    obstacle
    {{
        type            noSlip;
    }}
    frontAndBack
    {{
        type            empty;
    }}
}}
""",
            cls="volVectorField",
        ),
        encoding="utf-8",
    )

    (case / "0.orig" / "p").write_text(
        foam(
            "p",
            """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    inlet
    {
        type            zeroGradient;
    }
    outlet
    {
        type            fixedValue;
        value           uniform 0;
    }
    top
    {
        type            symmetryPlane;
    }
    bottom
    {
        type            symmetryPlane;
    }
    obstacle
    {
        type            zeroGradient;
    }
    frontAndBack
    {
        type            empty;
    }
}
""",
            cls="volScalarField",
        ),
        encoding="utf-8",
    )

    allrun = r"""#!/bin/bash
set -euo pipefail
cd "${0%/*}" || exit 1
sed -i 's/\r$//' "$0" 2>/dev/null || true

DIR="$(cd "$(dirname "$0")" && pwd)"
while [ "$DIR" != "/" ]; do
    if [ -f "$DIR/cfd/env.sh" ]; then
        # shellcheck disable=SC1091
        source "$DIR/cfd/env.sh"
        break
    fi
    DIR="$(dirname "$DIR")"
done

rm -rf processor* VTK postProcessing constant/polyMesh
[ -d 0 ] && rm -rf 0
cp -r 0.orig 0
blockMesh
snappyHexMesh -overwrite
cp -f 0.orig/U 0/U
cp -f 0.orig/p 0/p
checkMesh | tee log.checkMesh
icoFoam | tee log.icoFoam
foamToVTK -useTimeName | tee log.foamToVTK
"""
    with (case / "Allrun").open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(allrun.replace("\r\n", "\n"))
    with (case / "Allclean").open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("#!/bin/bash\ncd \"${0%/*}\" || exit 1\nrm -rf 0 processor* VTK postProcessing constant/polyMesh log.*\n")

    meta = {
        "case_id": case_id,
        "shape": shape,
        "Re": Re,
        "cx": cx,
        "cy": cy,
        "D": D,
        "U_inf": U,
        "nu": nu,
        "St_ref": 0.16 if abs(Re - 100) < 40 else None,
        "Cd_ref_Re100": 1.33,
    }
    (case / "meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return case


def expand_matrix(cfg: dict) -> list[dict]:
    phys = cfg["physics"]
    jobs = []
    for Re in phys["Re_list"]:
        for cy in phys.get("cy_offsets", [0.0]):
            for scale in phys.get("D_scales", [1.0]):
                jobs.append(
                    {
                        "Re": float(Re),
                        "cx": float(phys["cx"]),
                        "cy": float(cy),
                        "D": float(phys["D"]) * float(scale),
                        "shape": phys["shape"],
                    }
                )
    return jobs


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--config", default=str(ROOT / "configs" / "default.yaml"))
    p.add_argument("--re", type=float, default=None)
    p.add_argument("--all-matrix", action="store_true")
    p.add_argument("--out", default=None)
    args = p.parse_args()
    cfg = load_config(args.config)
    out = Path(args.out) if args.out else resolve_under_root(cfg, "data_raw") / "cases"
    out.mkdir(parents=True, exist_ok=True)
    jobs = expand_matrix(cfg) if args.all_matrix else [
        {
            "Re": float(args.re or 100),
            "cx": float(cfg["physics"]["cx"]),
            "cy": float(cfg["physics"]["cy"]),
            "D": float(cfg["physics"]["D"]),
            "shape": cfg["physics"]["shape"],
        }
    ]
    for job in jobs:
        path = write_case(cfg, out, **job)
        print(path)


if __name__ == "__main__":
    main()
